Makefile
hook-tests/029-fix-ld-so-symlink.test
hooks/029-fix-ld-so-symlink.chroot
snapcraft.yaml

Fixing native arch links is not enough, as we also must fix links off armhf/i386 on arm64/amd64.

Adjust all symlinks, including multiarch ones.

---

static/usr/lib/core20/run-snapd-from-snap

If state.json exists, but snapd.service doesn't, then we were likely
interrupted before the snapd-seeding from /tmp was able to bootstrap the
full snapd from the snap, so we still need to do that now.
Fixes: https://bugs.launchpad.net/snapd/+bug/1845310
Signed-off-by: Ian Johnson <ian.johnson@canonical.com>

run-snapd-from-snap: check for snapd.service existing too

---

static/etc/system-image/writable-paths

Ogra reported that /etc/environment is not writable on uc20 based
systems. This commit fixes this. We also noticed this in our spread test.

static: add /etc/environment to writable-paths

---

static/usr/lib/core20/run-snapd-from-snap

With https://github.com/snapcore/snapd/pull/7957 snap-boostrap
will mount the "correct" snapd snap to /run/mnt/snapd. With that
in place we can simplify the run-snapd-from-snap script and also
avoid potentially mounting a random snapd snap when there are
multiple recovery systems.
This commit keeps the old way of doing things for compatiblity
but once the snapd PR is merged we can remove the compat code.

static: try using /run/mnt/snapd first in run-snapd-from-snap

---

static/usr/lib/systemd/system/debug-shell.service.d/core-override.conf
static/usr/lib/systemd/system/emergency.service.d/core-override.conf
static/usr/lib/systemd/system/emergency.target.d/core-override.conf

Disable emergency.target & debug-shell, unless kernel cmdline is dangerous
systemctl start debug-shell => simply fails
systemctl isolate emergency.target => reboots the system

Disable emergency.target & debug-shell, unless kernel cmdline is dangerous

---

hooks/200-console-conf-after.chroot

Once https://github.com/CanonicalLtd/subiquity/pull/638 lands and console-conf is rebuilt there should be no need for the hacks to ensure the correct ordering. However, leave the verification in place, so that the things do not get mysteriously broken.

hooks/200-console-conf-after.chroot: perform console-conf ordering checks

---

static/usr/lib/core/run-snapd-from-snap

The mentioned PR was merged, so we don't need this code anymore.

run-snapd-from-snap: don't try to load a snapd snap from the seed anymore

---

hooks/014-set-motd.chroot

Dynamic motd update via pam_motd is already disabled on core 18. Do it for
core20 too.
Cleanup a dangling symlink to motd-news.timer which is already removed by the
hooks.

hooks/motd: disable dynamic motd, cleanup dangling symlink

---

hook-tests/020-extra-files.test
hooks/020-extra-files.chroot

The mounts from the host system will be placed under the /host directory.

ensure that /host exists

---

static/etc/system-image/writable-paths

This is intended to support https://github.com/snapcore/snapd/pull/6258.
In order to have dbus-daemon look for service activation files under /var/lib/snapd, we need to drop configuration fragments into `/etc/dbus-1/session.d` and `/etc/dbus-1/system.d`. The latter was already writable so the dbus interface can poke holes in the system bus security policy, but the former was not.
Since core20 has not been finalised yet, I've changed the existing `/etc/dbus-1/system.d` writable path to `/etc/dbus-1`, to save a bind mount.

static: make all of /etc/dbus-1 writable

---

hook-tests/020-extra-files.test

The test used absolute paths and actually tested things on the host, not inside
the test root.

hook-tests: fix extra files test

---

hook-tests/001-extra-packages.test
hooks/001-extra-packages.chroot
snapcraft.yaml

This is need on rpi where we have filesystems that are vfat in the gadget.
Also useful for running fsck on UC20.
Fixes https://github.com/snapcore/core20/issues/37

001-extra-packages.chroot: add dosfstools to get mkfs.vfat

---

Makefile
static/usr/lib/core/handle-writable-paths
tests/test_ubuntu-core-rootfs.sh

The new handle_writable_defaults() helper will take the defaults
from $writable/system-data/_writable_defaults/ and apply them on top of
the populated $writable/system-data.
This will allow providing image defaults in a clean way.
This is https://github.com/snapcore/core-build/pull/59 for UC20.

static: add new handle_writable_defaults() to handle-writable-paths

---

Makefile
hooks/001-extra-packages.chroot

When building snap in launchpad, one can specify build archive
(Primary or PPA), and specify if release/security/updates/proposed
should be used for a given snap build.
Use that information during core20 snap build. This way, one can
rebuild core20 snap in personal PPAs, or rebuild it with Proposed
enabled, without any sourcecode/snapcraft.yaml modifications.

Copy-in launchpad's build-archive

---

static/usr/bin/man

Instead of the generic minimized message use a more custom
one.
This will fix https://github.com/snapcore/core20/issues/57

static: provide friendly message when "man" is used

---

Makefile
hooks/001-extra-packages.chroot
snapcraft.yaml

subiquity snap is built with snapcraft from git + archive deps.
core20 installs consoleconf from the archive, however core20 is a
snap, and it should build consoleconf from git too just like
subiquity.
Signed-off-by: Dimitri John Ledkov <xnox@ubuntu.com>
I did two builds, of the current core20 and with this change applied.
$ sudo diff -ru old/ new/ 2>/dev/null | filterdiff -X '*.pyc' | diffstat
manifest.yaml  |  407 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++--
snapcraft.yaml |   28 ++++++++++++
2 files changed, 431 insertions(+), 4 deletions(-)
The net change is timestamps of .pyc files + manifest & snapcraft, otherwise the core20 snap is …

Build consoleconf from git

---

static/etc/system-image/writable-paths

This will fix https://bugs.launchpad.net/snappy/+bug/1880698
by ensuring that the original content gets copied up.

static: make /etc/writable mode "transition" in writable-paths

---

hooks/030-fix-timedatectl.chroot
tests/test_etc-writable-symlinks.sh

The 030-fix-timedatectl.chroot hook was doing too much, there are
reasonable defaults already from the downloaded focal.tar.gz so
we should just use them. This will also fix the issue that the
store is blocking the upload because the localtime symlink
changed.
This reverts parts of #49 but add tests to ensure we don't regress.

hooks: remove redundancy from timezone settings

---

hook-tests/001-extra-packages.test
hooks/001-extra-packages.chroot

gdbserver is needed in order to use the new `snap run --experimental-gdbserver` feature. Specifically, using gdbserver is much smaller than adding the full gdb package to the base snap, and allows remote gdb debugging on Ubuntu Core.
See also https://forum.snapcraft.io/t/new-experimental-snap-run-experimental-gdbserver-option/18227
Note that I tested adding both this package and the `gdb` package to the core20 snap and found these sizes:
```
$ ls -la *.snap
-rw-rw-r-- 1 user user 64000000 Jul 20 20:27 core20_upstream.snap
-rw-r--r-- 1 user user 64233472 Jul 20 20:34 core20_gdbserver.snap
-rw-r--r-- 1 user user 69267456 Jul 21 08:51 core20_gdb.snap
```
core18 PR: https://github.com/snapcore/core18/pull/163

hooks/001-extra-packages.chroot: add gdbserver

---

hooks/001-extra-packages.chroot
static/usr/lib/systemd/system/core.start-snapd.service
static/usr/lib/systemd/system/secureboot-db.service.d/core-override.conf

Only execute it in install mode, and ensure this is done before snapd
is started.
The goal is to have dbxupdates applied before install is performed,
such that we seal against the latest dbx state possible.

Add secureboot-db package, try #2.

---

static/etc/system-image/writable-paths

This commit move /etc/cloud from a synced dir to a persistent
dir. Synced dirs have strange semantics, e.g. the user cannot
remove a file that is also present in the core20 snap in the
dir without it coming back on the next reboot. Hence we want
to avoid any synced dirs.
This requires the following prereqs:
https://github.com/snapcore/core20/pull/46
https://github.com/snapcore/snapd/pull/8612
first.

static: switch /etc/cloud from synced to persistent

---

hooks/900-cleanup-etc-var.chroot

Core currently has a symlink /etc/sysctl.conf.d/99-sysctl.conf that
points to /etc/sysctl.conf. This file is removed by the core build
so removing this symlink is also needed.
Note that the sysctl.conf file is not writable on core and it
only contains commented out entries.

hooks: fix broken symlink /etc/sysctl.conf.d/99-sysctl.conf

---

.travis.yml

We can't use sudo snapcraft with snapcraft 4.0, and we should ideally be building with lxd, as that provides us with the right build-base for building the snap, regardless of what series travis currently supports.
Also we need snapcraft 4.1.2 to take advantage of snapcraft intercepting the mknod calls, otherwise the lxd container fails when trying to run the chroot things.
Fixes https://github.com/snapcore/core20/issues/66

.travis.yml: use snapcraft w/ lxd to build the snap

---

hooks/900-cleanup-etc-var.chroot

This configuration file has the following contents:
```
datasource_list: [ NoCloud, ConfigDrive, OpenNebula, DigitalOcean, Azure, AltCloud, OVF, MAAS, GCE, OpenStack, CloudSigma, SmartOS, Bigstep, Scaleway, AliYun, Ec2, CloudStack, Hetzner, IBMCloud, Oracle, Exoscale, RbxCloud, None ]
```
On Ubuntu Core, one cannot run dpkg-reconfigure for one, so the file can never
be modified in practice, and additionally we do not want to allow all possible
datasources under the sun without understanding their use cases in Ubuntu Core.
Note that already on Ubuntu Core, snapd as of 2.45.2 will write a configuration
file zzzz_snapd.cfg taking priority over this file to restrict the set of
datasources to a safe one, so we do not strictly need to delete this file, but
it will be simpler if we don't have …

hooks/900-cleanup-etc-var.chroot: rm cloud-init config file which we don't want

---

hooks/991-no-synced-dirs.chroot

Using "synced" in the writable-path something we do not want to
do in UC20. The user-experience is quirky, i.e. you can never
remove a file from a synced dir if that file is also available
via the underlying core snap. It will just reappear in the next
boot.

hooks: enable check that we do not use "synced" dirs

---

static/etc/system-image/writable-paths

We still need files from the core20 snap to show up in writable for /etc/cloud,
otherwise cloud-init does not work correctly out-of-the-box. As such, use
transition instead of none, which will copy files from the core20 snap to
/etc/cloud on writable.
This fixes a bug introduced as part of #54 and will fix cloud-init with uc20 again.

static/writable-paths: use transition instead of none for /etc/cloud

---

hook-tests/014-set-motd.test
hooks/014-set-motd.chroot

As outlined in [bug #1888575][0], the configuration file for motd-news was split out into a separate `motd-news-config` package.  It looks like that package is no longer being included in the core20 image, which breaks the build:
```
2020-09-04T01:55:34.2385780Z + sed -i s/ENABLED=1/ENABLED=0/g /etc/default/motd-news
2020-09-04T01:55:34.2398295Z sed: can't read /etc/default/motd-news: No such file or directory
2020-09-04T01:55:34.2402226Z + exit 1
2020-09-04T01:55:34.2405398Z make: *** [Makefile:35: install] Error 1
```
As the hooks were trying to disable the feature, I've just adjusted the hooks to not try and patch motd-news's config file, and verify that it isn't present with a test.
[0]: https://bugs.launchpad.net/ubuntu/+source/base-files/+bug/1888575

hooks: adapt to motd-news-config not being included in image any more

---

hooks/000-provide-uids-gids.chroot
hooks/990-ensure-uids-gids.chroot

This will allow users to add themselves to the docker group. This in combination
with an upgraded getent which reads from extrausers will allow the docker snap
to be used with non-root users.
Fixes: https://github.com/snapcore/core20/issues/72

[RFC] hooks: mv docker user/group definition to extrausers

---

static/etc/system-image/writable-paths

This file is used to manage wireless regulatory domains, so it should be
writable to allow setting REGDOMAIN in this file.
Forward-port to UC20 of https://github.com/snapcore/core/pull/117

static/writable-paths: make /etc/default/crda writable

---

.travis.yml

The associated fix has now been released and we can go back to using snapcraft
from stable again.

.travis.yml: use stable snapcraft now

---

snapcraft.yaml

As in the description. We have the same scheme (implementation as well) in core18 right now.

Make the version number date-based.

---

hooks/500-create-xdg.chroot

Update to the current version of https://github.com/snapcore/snapd/blob/master/tests/lib/snaps/test-snapd-xdg-settings/bin/xdg-settings-wrapper which supports subcommands
Currently settings the default mailto handler from thunderbird fails because the installed wrapper doesn't handle subcommands, which was added in snapd with https://github.com/snapcore/snapd/pull/7129 but the core wrapper never got updated
Testcase
$ snap install thunderbird
$ xdg-settings set default-url-scheme-handler mailto thunderbird_thunderbird.desktop
$ snap run --shell thunderbird
$ xdg-settings get default-url-scheme-handler mailto
$ xdg-settings get default-url-scheme-handler mailto
NOT-THIS-SNAP.desktop
$ dbus-send --session --dest=io.snapcraft.Settings --type=method_call --print-reply /io/snapcraft/Settings …

hooks: update xdg-settings to support subcommands

---

.github/workflows/test.yaml

This PR contains a port of the Travis CI workflow over to Github Actions.  As the travis-ci.org website has a big banner saying that it will soon be shut down, it seems prudent to move to an alternative.
I've made use of the `snapcore/action-build@v1` action in the workflow, which takes care of installing Snapcraft and running the build via LXD (so it is isolated from the Ubuntu install on the Github runner).  The workflow is set to run on pull requests and pushes to branches matching `master*`.  It won't run for this pull requests until the target branch contains the workflow though.
A sample run from my own repository can be seen here:
https://github.com/jhenstridge/core20/actions/runs/766038505
If this looks interesting, it should be pretty easy to copy for core, core18 and core22.

ci: add a Github Actions port of the Travis workflow

---

Makefile
hook-tests/013-add-mdns-hostname-resolution.test
hooks/001-extra-packages.chroot
hooks/012-add-foreign-libc6.chroot
hooks/013-add-mdns-hostname-resolution.chroot
snapcraft.yaml

This PR draft attempts to add optional support for mDNS hostname resolution via Avahi.  In order for it to be useful, Avahi will have to be available (either provided by the distro on classic systems, or via the avahi snap on Core).  If Avahi is not available, the plugin will fail quickly when it can't connect to `/run/avahi-daemon/socket`.
The AppArmor `<abstractions/nameservice>` policy fragment allows communication with this socket, so any snap plugging `network` already has the permissions it needs to communicate with Avahi's hostname resolution socket (which is heavily constrained compared to the D-Bus API).

hooks: add mDNS hostname resolution support

---

hooks/900-cleanup-etc-var.chroot

Previously everything was deleted from profile.d
Now only cloud-init things are deleted.
This leaves base-files' profile.d hook to ensure locales are set and bash-completion hook that enables bash-completion.
We have had previously requests to re-enable bash-completion. We install it, and don't activate it by default.

Resurrect bash-completion

---

hook-tests/200-enable-time-wait-sync.test
hooks/200-enable-time-wait-sync.chroot

It looks like adding 105 broke GCE tests. It's unclear why right now, the change works inside qemu. But to unbreak master we need to go back and revert this change.
I'm running a spread test with the services removed please do not merge before this is finished.

hooks: revert PR#105 - it seems to 

---

Makefile

We will need to copy the yaml file in order to be able to gather it from the Buildd output folder.

Copy dpkg yaml for buildd

---

hook-tests/024-configure-bootchart.test
hooks/001-extra-packages.chroot
hooks/024-configure-bootchart.chroot

In focal, there are no debs for gdbserver or systemd-bootchart, skip
installing those for now. Also there is no Ubuntu Core for riscv64
either, thus lack of these packages doesn't change featureset for now.
Signed-off-by: Dimitri John Ledkov <dimitri.ledkov@canonical.com>

Fix riscv64 build

---

README.md
hooks/024-configure-bootchart.chroot

Previously, we started systemd-bootchart by adding
systemd.wants=systemd-bootchart.service to the kernel command
line. This has as a side effect that the service is added to the
default target and is started later than desired. Instead, enable the
service by default and use a new kernel command line
parameter (core.bootchart) as condition to start it.

Start bootchart earlier

---

README.md
hooks/024-configure-bootchart.chroot

Use /var/log/debug/boot<N> for saving bootchars instead of the
ubuntu-save partition.

hooks: change folder where to save bootcharts

---

.github/workflows/test.yaml

Switch to self-hosted runners for Github Actions

---

hook-tests/020-extra-files.test
hooks/020-extra-files.chroot
static/etc/systemd/system.conf.d/11-snapd-ctrl-alt-del-burst.conf

Systemd provides two ctrl-alt-del keyboard hooks (enabled by default)
exposing Ubuntu Core to malicious reboot request attacks.
(1) Ctrl-alt-del single press
(2) Ctrl-alt-del burst (7 presses or more in 2 seconds)
These issues are acknowledged and one addressed in a systemd commit
(commit: 24dd31c19ede505143833346ff850af942694aa6, 231 and later) by providing
a config item for the systemd manager to disable the ctrl-alt-del burst action.
Issue (1) is addressed in snapd by allowing the ctrl-alt-del.target to be
masked (pull: https://github.com/snapcore/snapd/pull/11113)
Issue (2) is addressed in this patch by disabling burst action in the systemd
manager config using a drop-in configuration file.
Testing: The ctrl-alt-del kernel sequence sends a SIGINT to PID1 (systemd).
The burst sequence …

static: disable systemd ctrl-alt-del burst action

---

.github/pull_request_template.md

This should help inform contributors when we do bugfixes for core20 that might also be relevant for core22+.

Add a PR template that informs of core-base repository

---

hooks/001-extra-packages.chroot
hooks/600-no-debian.chroot

We now have a new HTTPS-capable domain for public PPAs, namely
ppa.launchpadcontent.net.  Adjust various bits of the build system to
accept that.

Handle PPAs being served from ppa.launchpadcontent.net

---

hooks/020-extra-files.chroot

Snaps using the cups interface with the cups snap as of snapd 2.55 will create
a bind mount of /run/cups -> /var/cups, which since /var/cups does not exist
will trigger the writable mimic code to create a writable mimic on /var. This
results in a fair amount of extra bind mounts for every directory in /var, so
creating this directory empty in the base snap ensures that no writable mimic
need be created.
Note that this will result in review-tools complaining when this is merged and a 
new core20 is uploaded since a new directory is being added to the base snap,
but this is okay.

hooks: mkdir /var/cups to avoid writable mimic creation for snaps using cups

---

Makefile

When there is no RTC systemd will use either it's own build date
or `/usr/lib/clock-epoch` to "seed" the initial time. So far we
did not create /usr/lib/clock-epoch but this commit adds it.
Thanks for helping us make a better ubuntu core!
This should also get cherry picked for core22+

Makefile: create /usr/lib/clock-epoch

---

hooks/001-extra-packages.chroot
hooks/400-trim-pkcs-11.chroot

Add pkcs11 dependencies into core20 base snap
Signed-off-by: Ondrej Kubik <ondrej.kubik@canonical.com>
Thanks for helping us make a better ubuntu core!
Before continuing with the PR, you might want to consider also creating a PR for the new core-base repository
at https://github.com/snapcore/core-base, which contains newer core versions (22+), if the PR is also relevant
for newer core versions.

core: add pkcs11 dependencies

---

static/usr/libexec/core/get-arg

Anything with and "A" or a "0" in the name was not parsed correctly and interpreted as a space instead.
Backport of https://github.com/snapcore/core-base/pull/129

get-arg: fix call to printf

---

hook-tests/600-no-debian.test
hooks/001-extra-packages.chroot

secureboot-db was copied to ucdev. This will make it easier for the team to add custom packages as we need now a patched version of systemd.

Use ucdev ppa instead of ubuntu-image

---

static/usr/lib/core/rtc-sys-time-init
static/usr/lib/udev/rules.d/90-rtc-sys-time-init.rules

Two optimization here:
* We filter `IMPORT{cmdline}`. This causes some system calls. On core20, it also reads UEFI variables. This is very slow. We used to read the cmdline on all device. Now we do it only on rtc devices.
* We stop calling `/usr/bin/systemd-escape`.
The first optimization is the most effective part. On google cloud, we reduce the time to cold boot devices from around 30s to 4s.

90-rtc-sys-time-init.rules: Optimize

---

static/usr/lib/systemd/system/snapd.autoimport-device@.service
static/usr/lib/udev/rules.d/66-snapd-autoimport.rules

This is a backport of https://github.com/snapcore/core-base/pull/35 and https://github.com/snapcore/core-base/pull/165
Currently, user assertions do not work on first boot which make snapd spread test fail. The reason is because it tries to run "snap" command before snapd is mounted. The issue does not appear to be a problem on UC 22, because the service has implicit dependencies to snapd being mounted. So let's do the same on UC 20.
Original commit message:
`snap auto-import` cannot run anymore because of sandboxing of systemd-udevd. Instead we need to schedule a systemd service.
Thanks for helping us make a better ubuntu core!
Before continuing with the PR, you might want to consider also creating a PR for the new core-base repository
at https://github.com/snapcore/core-base, which …

Stop running auto-import directly from udevd

---

static/usr/bin/core-sshd-host-keygen

remove perl dependency in base snap
Signed-off-by: Ondrej Kubik <ondrej.kubik@canonical.com>
Thanks for helping us make a better ubuntu core!
Before continuing with the PR, you might want to consider also creating a PR for the new core-base repository
at https://github.com/snapcore/core-base, which contains newer core versions (22+), if the PR is also relevant
for newer core versions.

static: remove perl dependency

---

static/usr/lib/core/run-snapd-from-snap

Needed by https://github.com/snapcore/snapd/pull/13370
Backport of https://github.com/snapcore/core-base/pull/184

run-snapd-from-snap: set the current symlink before bootstrapping

---

static/usr/lib/systemd/system/snapd.autoimport-device@.service

Backport of https://github.com/snapcore/core-base/pull/173
There is a conflict between snapd.autoimport.service and snapd.autoimport-device@.service. This causes error messages because both cannot mount in the same time. So they cannot be run at the same time.

snapd.autoimport-device@.service: do not run along snapd.autoimport.service

---

static/usr/lib/core/run-snapd-from-snap

The new FDE manager needs access the kernel keyring to access the primary key. That includes seeding.
Backport of https://github.com/canonical/core-base/pull/229

run-snapd-from-snap: seed with access to keyring

---

snapcraft.yaml

This is now being introduced to make sure snapd no longer uses apparmor from the base, as a breaking change was made by closing a security hole.
The update that breaks older snapds (snapd < 2.60). Vendoring enabled in 2.60: https://github.com/canonical/snapd/pull/12543
Now why 2.61? Because 2.61 is supported all the way back to Xenial, so we can safely require this without running into compatiblity issues there. However this avoids us having users that intentionally stay behind on their snapd version but keeps updating their base snaps.
```
apparmor (2.13.3-7ubuntu5.4) focal-security; urgency=medium
* SECURITY UPDATE: Excessive permissions with mount rules (LP: #1597017)
- d/p/CVE-2016-1585/parser-Fix-expansion-of-variables-in-unix-rules-addr.patch:
add calls to filter_slashes() in …
```

snapcraft: require snapd 2.61+ going forward for new core20 releases

---

static/usr/lib/core/run-snapd-from-snap

Now we will mount the snapd snap in /snap/snapd/ on first boot to avoid duplicate mounts. Adapt to this initramfs changes.
Backport of https://github.com/canonical/core-base/pull/255.

static/run-snapd-from-snap: adapt to new mount place for snapd snap

---

SECURITY.md

Core20 version of our security.md
Backport of https://github.com/canonical/core-base/pull/328

SECURITY.md: add our security documentation for the core20 snap
